name: CI Code Checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (excluding node_modules)
        run: npx eslint frontend/src --ext .js,.jsx || true

      - name: Run Prettier (excluding node_modules)
        run: npx prettier . --check || true

      - name: Run Markdown Validation
        run: node scripts/validate-md.js || true
