name: CI Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - Show working directory
        run: |
          echo "Current directory: $(pwd)"
          ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run ESLint
        run: npx eslint .
        working-directory: ./frontend

      - name: Run Prettier check
        run: npx prettier --check .
        working-directory: ./frontend

      - name: Run Markdown rule check
        run: node scripts/check-md-rules.js || echo "Markdown rule check skipped"

      - name: Markdown契約・設計チェック
        run: node scripts/validate-md.js || echo "契約チェック skipped"
