name: CI Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: ESLint & Prettier fix
        run: |
          npx eslint . --fix
          npx prettier --write .
      - name: Markdown rule update
        run: node scripts/auto-update-md-rules.js
      - name: Markdown rule validate
        run: node scripts/validate-md.js
